config/routes.rb
Rails.application.routes.draw do
  resources :locations

  root 'locations#new'

end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :my_location
  validates :address, :city, presence: true
  after_validation :geocode

  def my_location
    "#{address}, #{city}, GA"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  include LocationsHelper
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    # Marta API URL
    source = 'http://developer.itsmarta.com/BRDRestService/RestBusRealTimeService/GetAllBus'

    # Use our helper method to parse the data from the API
    @buses = fetch_api_data(source)

    # Loop through all buses and return only those that are nearby
    @nearby_buses = []

    @buses.each do |bus|
      user_lat = @location.latitude
      user_long = @location.longitude
      bus_lat = bus['LATITUDE'].to_f
      bus_long = bus['LONGITUDE'].to_f
      if is_nearby?(user_lat, user_long, bus_lat, bus_long)
        @nearby_buses << bus
      end
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :city, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
  # Parse the API data to store it in an array of hashes
  # so that each bus is a hash
  def fetch_api_data(source)
    http = Net::HTTP.get_response(URI.parse(source))
    data = http.body
    JSON.parse(data)
  end

  # Compare the user latitude and longitude with a bus
  # to see if it is nearby (within 0.01 degrees lat / lon)
  # TODO: Make this a true circular radius
  # TODO: Give user option of how close
  def is_nearby?(user_lat, user_long, bus_lat, bus_long)
    (user_lat - bus_lat).abs <= 0.01 && (user_long - bus_long).abs <= 0.01
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Escape Bus</title>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_maps_api_key'] %>"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container-fluid">

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<div>
  <div class="col-xs-12 well">
    <%= form_for(@location) do |f| %>
      <% if @location.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

          <ul>
          <% @location.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="col-xs-12">
        <div class="field form-group">
          <%= f.label :address %><br>
          <%= f.text_field :address, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :city %><br>
          <%= f.select :city, options_for_select([
            'Atlanta',
            'Alpharetta',
            'Avondale Estates',
            'Chamblee',
            'Clarkston',
            'College Park',
            'Decatur',
            'Doraville',
            'Dunwoody',
            'East Point',
            'Ellenwood',
            'Fairburn',
            'Forest Park',
            'Hapeville',
            'Jonesboro',
            'Lake City',
            'Lovejoy',
            'Lithonia',
            'Morrow',
            'Palmetto',
            'Riverdale',
            'Roswell',
            'Sandy Springs',
            'Stone Mountain',
            'Union City'
          ]), {}, class: "form-control" %>
        </div>
      </div>
      <div class="form-actions text-center">
        <button class="btn btn-md btn-success">
          <%= ' Go ' %><% f.submit %>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/locations/edit.html.erb
<div class="row">
  <header class="jumbotron">
    <div class="container-fluid">
    </div>
  </header>

  <div class="col-xs-4 col-xs-offset-4">

    <p class="text-center">So, where are you, exactly?</p>

    <%= render 'form' %>

  </div>
</div>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.city %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<div class="row">
  <header class="jumbotron">
    <div class="container-fluid">
    </div>
  </header>

  <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">

    <p class="text-center">Wanna get away?<br>Tell us where you are and we'll show you all the nearby buses.</p>

    <%= render 'form' %>

  </div>
</div>

app/views/locations/show.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <a href="<%= new_location_path %>"><img src="<%= image_path 'escape_bus_logo.png' %>" alt="Escape Bus Logo" id="logo" class="img-responsive center-block"></a>
  </div>
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1 text-center well">
    <h2>You are standing at...</h2>
    <p><%= @location.my_location %></p>
    <div id="map-canvas" class="img-responsive" style="height:450px;width:450px;margin:auto;padding:0;"></div>

    <h2>The closest buses are...</h2>

    <% if @nearby_buses.empty? %>
      <p>...not really that close. Time to walk, bike, taxi, or Uber.</p>
    <% end %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <% @nearby_buses.each do |bus| %>
          <ul class="list-inline">
              <div class="panel panel-default">
            <li>
                <div class="panel-body">
                    <strong>Route: </strong><%= bus['ROUTE'] %> - <%= bus['DIRECTION'] %>
                    <br>
                    <strong>Bus Number: </strong><%= bus['VEHICLE'] %>
                    <br>
                    <strong>Next Stop: </strong><%= bus['TIMEPOINT'] %>
                    <br>
                </div>
            </li>
              </div>
          </ul>
        <% end %>
      </div>
    </div>

    <%= link_to 'Edit', edit_location_path(@location) %> |
    <%= link_to 'Back', new_location_path %>
  </div>
</div>

<script type="text/javascript">
  function initialize() {
    // User latitude and longitude
    var userLocation = new google.maps.LatLng(<%= @location.latitude %>, <%= @location.longitude %>);

    // Custom user icon
    var userIcon = "<%= image_path 'man_icon.png' %>";

    var mapOptions = {
     center: userLocation,
     zoom: 15
    };
     var map = new google.maps.Map(document.getElementById('map-canvas'),
       mapOptions);

     // Add user location marker to map
     var userMarker = new google.maps.Marker({
      position: userLocation,
      map: map,
      animation: google.maps.Animation.DROP,
      title: 'You Are Here',
      icon: userIcon
     });

     // Get all the nearby buses and convert to JSON
     var nearbyBuses = <%= raw @nearby_buses.to_json %>

     // Custom bus icon
     var busIcon = "<%= image_path 'bus_icon.png' %>"

     // Looping throught nearby buses to put markers on the map
     nearbyBuses.forEach(function (element){
      // Bus latitude and longitude
      var busLocation = new google.maps.LatLng(element['LATITUDE'], element['LONGITUDE']);

      // Bus marker
      var busMarker = new google.maps.Marker({
        position: busLocation,
        map: map,
        animation: google.maps.Animation.DROP,
        title: element['ROUTE'] + " - " + element['DIRECTION'],
        icon: busIcon
      });

      // Create info window for each marker
      var contentString = '<div id="content"><h2>Route ' + element['ROUTE'] +
        ' - ' + element['DIRECTION'] +
        '</h2><div id="bodyContent"><p>Next stop: ' +
        element['TIMEPOINT'] + '</p></div></div>';

      var infoWindow = new google.maps.InfoWindow({
        content: contentString
      });

      // Add an event listener to open the info window when the bus marker is clicked
      google.maps.event.addListener(busMarker, 'click', function(){infoWindow.open(map, busMarker);
      });
     });
   }
   google.maps.event.addDomListener(window, 'load', initialize);
 </script>